import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const outDir = path.dirname(fileURLToPath(import.meta.url));
const repo = 'D:/guanmai/ai_order_chatbot';
const b64 = (file) => `data:image/png;base64,${fs.readFileSync(path.join(repo, file)).toString('base64')}`;
const loginLogo = b64('apps/admin/public/login-logo.png');
const loginBg = b64('apps/admin/public/login-bg-art.png');

const CSS = `
:root{--primary:#1677ff;--primary2:#0363ff;--bg:#f5f5f5;--card:#fff;--line:#f0f0f0;--text:rgba(0,0,0,.88);--muted:rgba(0,0,0,.45);--sub:rgba(0,0,0,.65);--success:#52c41a;--warn:#faad14;--danger:#ff4d4f;--nav:#001529;--shadow:0 1px 4px rgba(0,0,0,.04)}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans SC","Microsoft YaHei",sans-serif;color:var(--text);font-size:14px;background:var(--bg)}button,input,select,textarea{font:inherit}button{cursor:pointer}.hidden{display:none!important}
.shell{height:100vh;display:flex;overflow:hidden}.sider{width:52px;flex:0 0 52px;background:var(--nav);color:#fff;overflow:hidden}.brand{height:40px;display:grid;place-items:center;font-weight:700;font-size:14px}.nav{padding-top:4px}.nav a{height:52px;display:flex;align-items:center;justify-content:center;color:rgba(255,255,255,.76);text-decoration:none;position:relative;margin:4px 0}.nav a:hover,.nav a.active{color:#fff;background:var(--primary)}.nav a svg{width:22px;height:22px;stroke:currentColor;fill:none;stroke-width:1.8}.nav a span{display:none}.nav a:hover:after{content:attr(data-title);position:fixed;left:58px;background:#222;color:#fff;padding:5px 9px;border-radius:4px;font-size:12px;z-index:30;white-space:nowrap}.workspace{min-width:0;flex:1;display:flex;flex-direction:column}.header{height:40px;background:#fff;border-bottom:1px solid var(--line);padding:0 16px;display:flex;align-items:center;justify-content:space-between;flex:0 0 40px}.header .merchant{font-size:13px;font-weight:600}.header-actions{display:flex;gap:12px;align-items:center;color:var(--muted);font-size:12px}.icon-btn{border:0;background:transparent;color:var(--sub);padding:5px;border-radius:5px}.icon-btn:hover{background:#f5f5f5;color:var(--primary)}.tabbar{height:28px;background:#fff;display:flex;align-items:flex-end;flex:0 0 28px;overflow-x:auto}.route-tab{height:28px;padding:4px 10px;color:#707070;border:0;background:#fff;white-space:nowrap;font-size:13px}.route-tab.active{color:var(--primary2);background:#f5f5f5;border:1px solid var(--line);border-bottom-color:#f5f5f5;border-radius:6px 6px 0 0}.content{padding:12px;overflow:auto;min-height:0;flex:1}.page{max-width:1600px;margin:auto}.page-title{display:flex;align-items:flex-start;justify-content:space-between;margin:0 0 14px}.page-title h1{font-size:20px;margin:0;line-height:30px}.page-title p{margin:3px 0 0;color:var(--muted)}
.card{background:#fff;border:1px solid var(--line);border-radius:8px;box-shadow:var(--shadow);margin-bottom:12px}.card-head{min-height:46px;padding:11px 16px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:12px;font-weight:600}.card-body{padding:16px}.card.flat{box-shadow:none}.grid{display:grid;gap:12px}.grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.grid.four{grid-template-columns:repeat(4,minmax(0,1fr))}.grid.five{grid-template-columns:repeat(5,minmax(0,1fr))}.metric{padding:18px;background:#fff;border:1px solid var(--line);border-radius:8px}.metric-label{font-size:13px;color:var(--sub);margin-bottom:10px}.metric-value{font-size:28px;font-weight:700;line-height:1;color:#1f1f1f}.metric-note{color:var(--muted);font-size:12px;margin-top:8px}.blue{color:var(--primary)!important}.green{color:var(--success)!important}.orange{color:var(--warn)!important}.red{color:var(--danger)!important}
.toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.toolbar.right{justify-content:flex-end}.control{height:32px;border:1px solid #d9d9d9;border-radius:6px;padding:4px 10px;background:#fff;color:var(--text);min-width:120px;outline:none}.control:focus{border-color:#4096ff;box-shadow:0 0 0 2px rgba(5,145,255,.1)}textarea.control{height:auto;min-height:90px;resize:vertical}.search{min-width:240px}.btn{height:32px;border:1px solid #d9d9d9;background:#fff;border-radius:6px;padding:4px 14px;color:var(--text);display:inline-flex;align-items:center;justify-content:center;gap:6px}.btn:hover{border-color:#4096ff;color:#1677ff}.btn.primary{background:var(--primary);border-color:var(--primary);color:#fff}.btn.primary:hover{background:#4096ff;color:#fff}.btn.danger{color:var(--danger);border-color:#ffccc7}.btn.link{border:0;background:transparent;color:var(--primary);padding:2px 6px;height:auto}.btn.dashed{border-style:dashed}.btn.small{height:26px;font-size:12px;padding:2px 9px}.btn.block{width:100%}.tag{display:inline-block;padding:1px 7px;border-radius:4px;background:#f5f5f5;color:var(--sub);font-size:12px;line-height:20px;white-space:nowrap}.tag.blue{background:#e6f4ff}.tag.green{background:#f6ffed}.tag.orange{background:#fff7e6}.tag.red{background:#fff2f0}.tag.purple{background:#f9f0ff;color:#722ed1}.tag.cyan{background:#e6fffb;color:#08979c}.switch{width:34px;height:18px;border-radius:9px;background:#bfbfbf;border:0;position:relative;vertical-align:middle;padding:0}.switch:before{content:"";position:absolute;width:14px;height:14px;border-radius:50%;background:#fff;top:2px;left:2px;transition:.2s}.switch.on{background:var(--primary)}.switch.on:before{left:18px}
.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;min-width:760px}.table th{background:#fafafa;color:var(--sub);font-weight:600;text-align:left;padding:11px 12px;border-bottom:1px solid var(--line);white-space:nowrap}.table td{padding:11px 12px;border-bottom:1px solid var(--line);vertical-align:middle}.table tr:hover td{background:#fafafa}.table .mono{font:12px ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--sub)}.table .strong{font-weight:600}.empty{text-align:center;color:var(--muted);padding:42px}.pager{display:flex;justify-content:flex-end;gap:6px;padding:12px 0 0}.pager button{width:30px;height:30px;border:1px solid #d9d9d9;border-radius:6px;background:#fff}.pager button.active{border-color:var(--primary);color:var(--primary)}
.proto-tabs{display:flex;gap:0;border-bottom:1px solid var(--line);margin-bottom:16px;overflow:auto}.proto-tab{padding:10px 16px;border:0;background:transparent;color:var(--sub);position:relative;white-space:nowrap}.proto-tab.active{color:var(--primary)}.proto-tab.active:after{content:"";height:2px;background:var(--primary);position:absolute;left:10px;right:10px;bottom:-1px}.tab-panel{display:none}.tab-panel.active{display:block}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px 18px}.field{display:flex;flex-direction:column;gap:6px}.field.full{grid-column:1/-1}.field label{color:var(--sub)}.field label.required:before{content:"*";color:var(--danger);margin-right:4px}.field .control{width:100%}.help{font-size:12px;color:var(--muted)}.divider{height:1px;background:var(--line);margin:16px 0}.alert{border:1px solid #91caff;background:#e6f4ff;border-radius:8px;padding:10px 14px;color:#0958d9;margin-bottom:12px}.alert.warn{background:#fffbe6;border-color:#ffe58f;color:#ad6800}.alert.danger{background:#fff2f0;border-color:#ffccc7;color:#cf1322}
.modal-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:100;display:none;align-items:center;justify-content:center;padding:20px}.modal-backdrop.open{display:flex}.modal{width:min(680px,96vw);max-height:90vh;background:#fff;border-radius:10px;box-shadow:0 12px 40px rgba(0,0,0,.2);display:flex;flex-direction:column}.modal.wide{width:min(1060px,96vw)}.modal-head{padding:15px 20px;border-bottom:1px solid var(--line);font-size:16px;font-weight:600;display:flex;justify-content:space-between}.modal-body{padding:20px;overflow:auto}.modal-foot{padding:12px 20px;border-top:1px solid var(--line);display:flex;justify-content:flex-end;gap:8px}.close{border:0;background:transparent;font-size:20px;color:var(--muted)}.toast{position:fixed;top:18px;left:50%;transform:translate(-50%,-15px);background:#fff;border-radius:8px;box-shadow:0 6px 24px rgba(0,0,0,.16);padding:10px 18px;opacity:0;pointer-events:none;transition:.25s;z-index:200}.toast.show{opacity:1;transform:translate(-50%,0)}
.progress{height:7px;background:#f0f0f0;border-radius:4px;overflow:hidden}.progress i{display:block;height:100%;background:var(--primary);border-radius:4px}.section-title{display:flex;align-items:baseline;gap:10px;margin:24px 0 12px}.section-title b{font-size:25px;color:#d9d9d9}.section-title h2{font-size:18px;margin:0}.section-title span{color:var(--muted)}.chart{height:230px;position:relative;background:linear-gradient(#fff,#fff),repeating-linear-gradient(to bottom,transparent 0,transparent 45px,#f0f0f0 46px);border-left:1px solid #ddd;border-bottom:1px solid #ddd;overflow:hidden}.chart svg{width:100%;height:100%}.chart-labels{display:flex;justify-content:space-between;color:var(--muted);font-size:11px;margin-top:6px}
.chat-layout{height:calc(100vh - 68px);display:grid;grid-template-columns:270px minmax(420px,1fr) 320px;background:#fff}.chat-side{border-right:1px solid var(--line);display:flex;flex-direction:column;min-width:0}.chat-side-head{padding:14px;border-bottom:1px solid var(--line)}.conversation{padding:12px 14px;border-bottom:1px solid #fafafa;cursor:pointer}.conversation.active{background:#e6f4ff}.conversation-title{font-weight:600;display:flex;justify-content:space-between}.conversation-preview{color:var(--muted);font-size:12px;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chat-main{display:flex;flex-direction:column;min-width:0}.chat-head{height:52px;border-bottom:1px solid var(--line);padding:0 16px;display:flex;align-items:center;justify-content:space-between}.messages{flex:1;padding:18px;overflow:auto;background:#f7f8fa}.bubble{max-width:72%;padding:9px 12px;border-radius:8px;background:#fff;margin:8px 0;box-shadow:0 1px 2px rgba(0,0,0,.05)}.bubble.me{margin-left:auto;background:#95ec69}.bubble .time{font-size:10px;color:var(--muted);margin-top:5px}.composer{padding:12px;border-top:1px solid var(--line);background:#fff}.composer textarea{width:100%;height:72px;border:0;resize:none;outline:none}.chat-info{border-left:1px solid var(--line);padding:16px;overflow:auto}.review-card{border:1px solid var(--line);border-radius:8px;margin-top:12px}.review-card h4{margin:0;padding:10px 12px;border-bottom:1px solid var(--line)}
.login-page{min-height:100vh;background:#eef3ff center/cover no-repeat;display:flex;align-items:center;padding:32px 8%;position:relative;overflow:hidden}.login-brand{position:absolute;left:3%;top:6%;width:180px}.login-left{width:55%;padding-left:4%;z-index:1}.slogan{font-size:52px;font-weight:800;letter-spacing:4px;background:linear-gradient(90deg,#16d9d0,#1266dd,#8b28e8);-webkit-background-clip:text;color:transparent;margin:0 0 12px}.login-sub{font-size:20px;margin-bottom:36px}.feature{display:flex;gap:14px;align-items:center;margin:20px 0}.feature-ico{width:44px;height:44px;background:#fff;border-radius:10px;display:grid;place-items:center;font-size:22px}.login-card{width:400px;background:rgba(255,255,255,.96);padding:56px 60px;border:1px solid rgba(255,255,255,.8);border-radius:22px;box-shadow:0 18px 50px rgba(70,90,160,.18);z-index:1}.login-card h2{text-align:center;margin:0 0 8px}.login-card .subtitle{text-align:center;color:#aaa;margin-bottom:32px}.login-card .control{height:48px;margin-bottom:18px;border-radius:10px}.login-card .btn{height:48px;border-radius:10px;font-weight:600;background:linear-gradient(100deg,#3f8cff,#7a24f6);border:0}.login-foot{text-align:center;color:#bbb;font-size:12px;margin-top:30px}
.report{max-width:1440px;margin:auto;background:#f5f5f5}.report-hero{background:linear-gradient(120deg,#14213d,#204e96);color:#fff;padding:26px;border-radius:10px;margin-bottom:16px}.report-hero h1{margin:0 0 5px}.rank{width:26px;height:26px;border-radius:50%;display:grid;place-items:center;background:#eee}.rank.top{background:#faad14;color:#fff}.app-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.app-card{padding:20px;border-radius:12px;background:#fff;border:1px solid var(--line);text-align:center;cursor:pointer}.app-card:hover{transform:translateY(-2px);box-shadow:0 6px 20px rgba(0,0,0,.08)}.app-ico{width:50px;height:50px;border-radius:14px;margin:0 auto 10px;display:grid;place-items:center;color:#fff;font-size:24px}.dashboard-banner{padding:22px 26px;border-radius:12px;background:linear-gradient(120deg,#eef4ff,#fff);margin-bottom:16px}.dashboard-banner h1{margin:0 0 8px;font-size:23px}
@media(max-width:900px){.grid.five,.grid.four,.grid.three{grid-template-columns:repeat(2,minmax(0,1fr))}.grid.two{grid-template-columns:1fr}.form-grid{grid-template-columns:1fr}.chat-layout{grid-template-columns:220px 1fr}.chat-info{display:none}.login-left{display:none}.login-page{justify-content:center}.login-card{width:min(420px,92vw)}.app-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:600px){.sider{display:none}.content{padding:8px}.header{padding:0 8px}.grid.five,.grid.four,.grid.three,.grid.two{grid-template-columns:1fr}.metric-value{font-size:24px}.chat-layout{grid-template-columns:1fr}.chat-side{display:none}.login-card{padding:42px 28px}.table{min-width:680px}}
`;

const ICONS = {
  home:'<path d="M3 11.5 12 4l9 7.5M5.5 10.5V20h13v-9.5M9.5 20v-6h5v6"/>',
  tasks:'<path d="M6 3h12v18H6zM9 8h6M9 12h6M9 16h4"/>',
  edit:'<path d="M5 4h10l4 4v12H5zM15 4v4h4M8 16l2.5-.5L17 9l-2-2-6.5 6.5z"/>',
  users:'<circle cx="8" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M2.5 20a5.5 5.5 0 0 1 11 0M13 20a4.5 4.5 0 0 1 8 0"/>',
  shop:'<path d="M4 9h16v11H4zM6 9l2-5h8l2 5M8 13h8M8 17h5"/>',
  code:'<path d="m8 8-4 4 4 4m8-8 4 4-4 4m-3-11-2 14"/>',
  chart:'<path d="M4 20V9m6 11V4m6 16v-7m4 7H2"/>',
  settings:'<circle cx="12" cy="12" r="3"/><path d="M12 3v3m0 12v3M3 12h3m12 0h3m-2.6-6.4-2.1 2.1M7.7 16.3l-2.1 2.1m12.8 0-2.1-2.1M7.7 7.7 5.6 5.6"/>',
  crown:'<path d="M3 7l4 4 5-7 5 7 4-4-2 12H5L3 7z"/>'
};
const icon = (name) => `<svg viewBox="0 0 24 24" aria-hidden="true">${ICONS[name] || ICONS.home}</svg>`;
const routeFiles = {
  '/':'home.html','/tasks':'tasks.html','/order-board':'order-board.html','/chat-simulator':'chat-simulator.html','/customers':'customers.html','/groups':'groups.html','/customer-groups':'customer-groups.html','/sku':'sku.html','/prompts':'prompts.html','/memory':'memory.html','/stats':'stats.html','/decision-dashboard':'decision-dashboard.html','/settings':'settings.html',
  '/admin/tenants':'admin-tenants.html','/admin/system-admins':'admin-system-admins.html','/admin/presets':'admin-presets.html','/admin/stats':'admin-stats.html','/admin/system':'admin-system.html'
};
const tenantNav = [
  ['/','home','首页'],['/tasks','tasks','订单审核'],['/chat-simulator','edit','订单录入'],['/customers','users','客户管理'],['/sku','shop','报价单'],['/prompts','code','提示词'],['/stats','chart','统计'],['/settings','settings','设置']
];
const adminNav = [
  ['/admin/tenants','shop','租户管理'],['/admin/system-admins','crown','系统管理员'],['/admin/presets','code','模版库'],['/admin/stats','chart','统计分析'],['/admin/system','settings','系统设置']
];
function navHtml(items, active){return items.map(([r,i,l])=>`<a href="${routeFiles[r]}" class="${active===r?'active':''}" data-title="${l}">${icon(i)}<span>${l}</span></a>`).join('')}
function shell(title, active, body, opts={}){
  const admin=opts.admin; const nav=admin?adminNav:tenantNav; const merchant=admin?'观麦平台管理中心':'观麦演示租户';
  return `<div class="shell"><aside class="sider"><div class="brand">AI</div><nav class="nav">${navHtml(nav,active)}</nav></aside><main class="workspace"><header class="header"><div class="merchant">${merchant}</div><div class="header-actions"><span>${admin?'系统管理员':'管理员 王明'}</span><button class="icon-btn" data-action="toast" data-message="原型：已退出登录">↪</button></div></header><div class="tabbar"><a class="route-tab" href="home.html">⌂</a><button class="route-tab active">${title}　×</button></div><section class="content">${body}</section></main></div>`;
}
const pageTitle=(t,sub='',extra='')=>`<div class="page-title"><div><h1>${t}</h1>${sub?`<p>${sub}</p>`:''}</div>${extra}</div>`;
const card=(t,b,e='')=>`<section class="card">${t?`<div class="card-head"><span>${t}</span>${e}</div>`:''}<div class="card-body">${b}</div></section>`;
const btn=(t,c='',attrs='')=>`<button class="btn ${c}" ${attrs}>${t}</button>`;
const tag=(t,c='')=>`<span class="tag ${c}">${t}</span>`;
const control=(ph,cls='')=>`<input class="control ${cls}" placeholder="${ph}">`;
const select=(items,cls='')=>`<select class="control ${cls}">${items.map(x=>`<option>${x}</option>`).join('')}</select>`;
function table(headers,rows,attrs='') {return `<div class="table-wrap"><table class="table" ${attrs}><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="pager"><button>‹</button><button class="active">1</button><button>2</button><button>›</button></div>`}
const metrics=(arr,cols='four')=>`<div class="grid ${cols}">${arr.map(([l,v,n='',c=''])=>`<div class="metric"><div class="metric-label">${l}</div><div class="metric-value ${c}">${v}</div>${n?`<div class="metric-note">${n}</div>`:''}</div>`).join('')}</div>`;
function tabs(items){return `<div class="tabs-scope"><div class="proto-tabs">${items.map((x,i)=>`<button class="proto-tab ${i===0?'active':''}" data-tab="${x[0]}">${x[1]}</button>`).join('')}</div>${items.map((x,i)=>`<div class="tab-panel ${i===0?'active':''}" data-panel="${x[0]}">${x[2]}</div>`).join('')}</div>`}
const field=(label,input,full=false,req=false,help='')=>`<div class="field ${full?'full':''}"><label class="${req?'required':''}">${label}</label>${input}${help?`<span class="help">${help}</span>`:''}</div>`;
function modal(id,title,content,wide=false){return `<div class="modal-backdrop" id="${id}"><div class="modal ${wide?'wide':''}"><div class="modal-head"><span>${title}</span><button class="close" data-close>×</button></div><div class="modal-body">${content}</div><div class="modal-foot">${btn('取消','','data-close')}${btn('确定','primary','data-save')}</div></div></div>`}
const chart=(color='#1677ff')=>`<div class="chart"><svg viewBox="0 0 800 230" preserveAspectRatio="none"><path d="M0 190 C90 170 110 110 190 135 S300 82 390 105 S520 45 610 78 S720 30 800 52" fill="none" stroke="${color}" stroke-width="3"/><path d="M0 190 C90 170 110 110 190 135 S300 82 390 105 S520 45 610 78 S720 30 800 52 L800 230 L0 230Z" fill="${color}18"/></svg></div><div class="chart-labels"><span>07-08</span><span>07-09</span><span>07-10</span><span>07-11</span><span>07-12</span><span>07-13</span><span>07-14</span></div>`;

const SCRIPT = `
document.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;
 if(t.matches('[data-tab]')){const root=t.closest('.tabs-scope');root.querySelectorAll(':scope > .proto-tabs > .proto-tab').forEach(x=>x.classList.remove('active'));root.querySelectorAll(':scope > .tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');const p=root.querySelector(':scope > [data-panel="'+t.dataset.tab+'"]');if(p)p.classList.add('active')}
 if(t.matches('[data-modal]')){const m=document.getElementById(t.dataset.modal);if(m)m.classList.add('open')}
 if(t.matches('[data-close]')){const m=t.closest('.modal-backdrop');if(m)m.classList.remove('open')}
 if(t.matches('[data-save]')){const m=t.closest('.modal-backdrop');if(m)m.classList.remove('open');toast('保存成功（原型演示）')}
 if(t.matches('.switch'))t.classList.toggle('on');
 if(t.matches('[data-action="toast"]'))toast(t.dataset.message||'操作成功');
 if(t.matches('[data-filter]')){const q=document.querySelector(t.dataset.filter)?.value?.toLowerCase()||'';document.querySelectorAll('tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none')}
 if(t.matches('[data-remove]')){const r=t.closest('tr');if(r)r.remove();toast('已删除（原型演示）')}
});
document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
function toast(msg){const x=document.getElementById('toast');x.textContent='✓ '+msg;x.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>x.classList.remove('show'),1800)}
document.querySelectorAll('[data-login]').forEach(b=>b.onclick=()=>location.href=b.dataset.login);
`;
function doc(title,body,extra=''){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}｜观麦 AI 智能订单助手</title><style>${CSS}${extra}</style></head><body>${body}<div id="toast" class="toast"></div><script>${SCRIPT}</script><script src="../business-specs.js"></script></body></html>`}

const pages = new Map();
const add=(file,title,html,extra='')=>pages.set(file,doc(title,html,extra));

// Public authentication pages
const loginBody=`<div class="login-page" style="background-image:url('${loginBg}')"><img class="login-brand" src="${loginLogo}" alt="观麦 AI"><section class="login-left"><h1 class="slogan">让录单&nbsp;&nbsp;更简单</h1><div class="login-sub">AI智能驱动，让每一张订单都精准高效</div><div class="feature"><div class="feature-ico">🤖</div><div><b>智能驱动</b><div class="help">AI识别订单信息，自动提取关键字段</div></div></div><div class="feature"><div class="feature-ico">⚡</div><div><b>极速响应</b><div class="help">毫秒级处理，录单效率提升80%</div></div></div><div class="feature"><div class="feature-ico">✓</div><div><b>自动纠错</b><div class="help">智能校验与补全，减少人为错误</div></div></div></section><section class="login-card"><h2>观麦 AI 智能订单助手</h2><div class="subtitle">登录审核后台</div><input class="control" aria-label="用户名" placeholder="请输入用户名"><input class="control" aria-label="密码" type="password" placeholder="请输入密码"><button class="btn primary block" data-login="home.html">登 录</button><div class="login-foot">——　安全 · 高效 · 智能　——</div></section></div>`;
add('login.html','登录',loginBody);
add('register.html','注册商户',`<div class="login-page" style="justify-content:center;background-image:url('${loginBg}')"><section class="login-card" style="width:480px;padding:38px 50px"><h2>注册商户</h2><div class="subtitle">创建您的审核后台账号</div><div class="form-grid" style="grid-template-columns:1fr">${field('商户名称',control('如：张记蔬菜配送'),false,true)}${field('您的姓名',control('显示名称'),false,true)}${field('登录用户名',control('用户名'),false,true)}${field('密码','<input class="control" type="password" placeholder="密码">',false,true)}</div><button class="btn primary block" style="margin-top:22px" data-action="toast" data-message="注册信息已提交（原型）">注 册</button><div class="login-foot">已有账号？ <a href="login.html">立即登录</a></div></section></div>`);
add('admin-login.html','系统管理员登录',`<div style="min-height:100vh;display:grid;place-items:center;background:#f0f2f5"><section class="card" style="width:460px;padding:22px"><div style="text-align:center;margin-bottom:18px"><h2 style="margin:0 0 4px">观麦 AI 智能订单助手</h2><span class="help">系统管理员登录</span></div>${tabs([['qr','企业微信扫码','<div style="height:240px;display:grid;place-items:center"><div style="width:180px;height:180px;background:repeating-linear-gradient(45deg,#111 0 4px,#fff 4px 8px);border:12px solid #fff;box-shadow:0 0 0 1px #ddd"></div></div>'],['pwd','账号密码',`<div style="padding:22px">${control('用户名','search')}<input class="control search" style="display:block;margin-top:16px" type="password" placeholder="密码"><button class="btn primary block" style="margin-top:18px" data-login="admin-tenants.html">登 录</button></div>`]])}</section></div>`);
add('admin-login-callback.html','扫码登录回调',`<div style="min-height:100vh;display:grid;place-items:center;background:#f5f5f5"><div class="card" style="width:520px;text-align:center;padding:52px"><div style="font-size:54px;color:#1677ff">◌</div><h2>正在完成扫码登录</h2><p class="help">正在校验企业微信授权信息，请稍候…</p><a class="btn primary" href="admin-tenants.html">返回管理后台</a></div></div>`);

// Tenant dashboard
const appCards=[['订单审核','tasks.html','#4facfe','审'],['订单录入','chat-simulator.html','#43e97b','录'],['客户管理','customers.html','#fa709a','客'],['群聊管理','groups.html','#ff9a9e','群'],['报价单','sku.html','#a18cd1','价'],['提示词','prompts.html','#667eea','词'],['AI 记忆','memory.html','#f093fb','忆'],['设置','settings.html','#91a6ff','设']];
const home=`<div class="page"><div class="dashboard-banner"><h1>下午好，观麦演示租户</h1><p>2026年7月14日 星期二 · 欢迎使用 AI 智能订单助手</p><div class="app-grid">${appCards.map(([n,f,c,i])=>`<a class="app-card" href="${f}" style="text-decoration:none;color:inherit"><div class="app-ico" style="background:${c}">${i}</div><b>${n}</b></a>`).join('')}</div></div><div class="grid two">${card('今日任务',metrics([['待处理','12','','orange'],['已完成','86','','green'],['失败','3','','red'],['活跃群','18','','blue']],'four'),'<a class="btn link" href="tasks.html">去处理 ›</a>')}${card('录单额度',`<div style="display:flex;justify-content:space-between;align-items:end"><div><div class="metric-value blue">8,642</div><div class="help">剩余额度</div></div>${tag('预计 31 天','blue')}</div><div class="progress" style="margin:16px 0"><i style="width:72%"></i></div><div class="help" style="display:flex;justify-content:space-between"><span>已用 3,358</span><span>总额 12,000</span></div>`)}</div>${card('群聊看板',table(['群聊名称','待处理','已完成','失败'],[['华南餐饮订货群','<b class="orange">6</b>','28','0'],['江北食堂订货群','2','18','<b class="red">1</b>'],['直营门店补货群','4','21','2'],['蔬菜采购群','0','19','0']]),'<a class="btn link" href="order-board.html">全部 ›</a>')}</div>`;
add('home.html','首页',shell('首页','/',home));

// Order review list and workbench
const taskRows=[
 [tag('待处理','orange'),'07-14 12:26','华南餐饮订货群','天河鲜食店','土豆20斤，前腿肉8斤，明早送','2','—','李娟','<a class="btn link" href="task-detail.html">详情</a> <button class="btn link" data-action="toast" data-message="已重新识别">重识别</button>'],
 [tag('已完成','green'),'07-14 11:48','江北食堂订货群','江北食堂','白菜两筐，鸡蛋5板','2','GM982711','陈林','<a class="btn link" href="task-detail.html">详情</a>'],
 [tag('失败','red'),'07-14 10:17','直营门店补货群','万象城门店','昨天一样，饮料少一点','0','—','王明','<a class="btn link" href="task-detail.html">详情</a> <button class="btn link red" data-remove>删除</button>'],
 [tag('合单','blue'),'07-14 09:56','华南餐饮订货群','天河鲜食店','追加香菜3斤','1','GM982742','李娟','<a class="btn link" href="task-detail.html">详情</a>']
];
const taskFilters=`<div class="toolbar"><input id="taskSearch" class="control search" placeholder="订单号 / 原文 / 门店"><input class="control" type="date" value="2026-07-14"><input class="control" type="date" value="2026-07-14">${select(['全部状态','识别中','待处理','已完成','失败','合单'])}${select(['全部群聊','我的群聊','华南餐饮订货群','江北食堂订货群'])}${select(['全部门店','天河鲜食店','江北食堂','万象城门店'])}${select(['全部审核员','李娟','陈林','王明'])}${btn('查询','primary','data-filter="#taskSearch"')}${btn('重置','','onclick="location.reload()"')}</div>`;
const taskPage=`<div class="page">${pageTitle('订单审核','查看 AI 识别订单并进行人工审核',`<div class="toolbar">${btn('刷新','','data-action="toast" data-message="列表已刷新"')}${btn('批量合单','primary','data-action="toast" data-message="请选择同一门店订单"')}</div>`)}${card('',taskFilters)}${card('',table(['状态','时间','群聊','门店','原文','商品数','观麦单号','审核员','操作'],taskRows,'data-search-table'))}</div>`;
add('tasks.html','订单审核',shell('订单审核','/tasks',taskPage));

const boardCustomers=[['天河鲜食店',tag('已识别','blue'),tag('待审核','orange'),'—'],['云岭酒店',tag('已识别','blue'),tag('已审核','green'),'GM982744'],['万象城门店',tag('识别中','orange'),'—','—']];
const groupCard=(name,pending,rows)=>`<section class="card"><div class="card-head"><span>${name} ${tag(pending+' 待处理','orange')}</span><button class="btn link" data-modal="groupTasks">任务记录 ›</button></div><div class="card-body">${table(['门店名','AI识别录入','人工审核','已下单'],rows)}</div></section>`;
const board=`<div class="page">${pageTitle('录单工作台','按群聊聚合查看客户录单进度',`<div class="toolbar">${select(['今天','昨天'])}${btn('刷新','','data-action="toast" data-message="看板已刷新"')}</div>`)}${card('',`<div class="toolbar">${select(['全部客户分组','重点客户','普通客户'])}${select(['全部审核员','李娟','陈林','王明'])}${control('搜索群聊或门店','search')}</div>`)}${groupCard('华南餐饮订货群',6,boardCustomers)}${groupCard('江北食堂订货群',2,[['江北食堂',tag('已识别','blue'),tag('已审核','green'),'GM982711'],['滨江员工餐厅',tag('已识别','blue'),tag('待审核','orange'),'—']])}</div>${modal('groupTasks','华南餐饮订货群 — 任务记录',table(['任务状态','门店名称','下单时间','审核员','操作'],[[tag('待处理','orange'),'天河鲜食店','12:26','李娟','<a class="btn link" href="task-detail.html">查看</a>'],[tag('已完成','green'),'云岭酒店','11:03','陈林','<a class="btn link" href="task-detail.html">查看</a>']]),true)}`;
add('order-board.html','录单工作台',shell('录单工作台','/tasks',board));

const orderItems=table(['客户原始输入','匹配商品','规格/单位','数量','单价','备注'],[['土豆','土豆（黄心）','斤','20','¥2.80','明早送'],['前腿肉','猪前腿肉','斤','8','¥15.60','去皮']]);
const taskBasic=`<div class="form-grid">${field('任务状态',tag('待处理','orange'))}${field('任务 ID','<span class="mono">OT-20260714-0012</span>')}${field('群聊','华南餐饮订货群')}${field('门店','天河鲜食店')}${field('下单时间','2026-07-14 12:26:18')}${field('审核员','李娟')}${field('消息类型',tag('纯文本','blue'))}${field('来源信道',tag('微信','green'))}${field('原始信息','<div class="alert">土豆20斤，前腿肉8斤，明早送天河店</div>',true)}</div>`;
const taskDetail=`<div class="page">${pageTitle('订单详情','OT-20260714-0012',`<div class="toolbar"><a class="btn" href="tasks.html">← 返回</a>${btn('AI 对比','','data-action="toast" data-message="已展开识别对比"')}${btn('确认提交','primary','data-modal="submitOrder"')}</div>`)}${card('',tabs([['basic','基本信息',taskBasic],['chat','群聊消息','<div class="messages" style="height:270px"><div class="bubble">@机器人 土豆20斤，前腿肉8斤，明早送天河店<div class="time">王老板 · 12:26</div></div><div class="bubble me">已识别 2 个商品，正在生成订单<div class="time">AI 助手 · 12:26</div></div></div>']]))}${card('订单商品',orderItems,`<div class="toolbar">${btn('新增商品','primary','data-modal="addItem"')}${btn('查看记忆','','data-modal="memoryDrawer"')}</div>`)}${card('识别与修正记录',table(['字段','AI 识别','人工修正','结果'],[['商品 1','土豆','土豆（黄心）',tag('已修正','orange')],['数量','20 斤','20 斤',tag('一致','green')]]))}</div>${modal('submitOrder','确认提交订单',`<div class="alert warn">订单将提交到观麦系统，请核对门店、商品与数量。</div><div class="form-grid">${field('收货日期','<input class="control" type="date" value="2026-07-15">')}${field('订单备注',control('可选'))}${field('通知群聊','<button class="switch on"></button>')}</div>`)}${modal('addItem','新增商品',`<div class="form-grid">${field('商品搜索',control('输入商品名 / SKU ID'),true,true)}${field('规格单位',select(['斤','件','箱']))}${field('数量','<input class="control" type="number" value="1">',false,true)}${field('备注',control('选填'),true)}</div>`)}${modal('memoryDrawer','客户记忆',table(['类型','内容','命中次数'],[[tag('修正记忆','orange'),'“前腿”默认匹配猪前腿肉','12'],[tag('下单习惯','cyan'),'默认单位为斤','28']]),true)}`;
add('task-detail.html','订单详情',shell('订单详情','/tasks',taskDetail));

// Chat simulator
const chat=`<div class="chat-layout"><aside class="chat-side"><div class="chat-side-head"><div class="proto-tabs" style="margin-bottom:10px"><button class="proto-tab active">客户</button><button class="proto-tab">群聊</button></div>${control('搜索客户','search')}</div><div class="conversation active"><div class="conversation-title"><span>天河鲜食店</span><small>12:26</small></div><div class="conversation-preview">土豆20斤，前腿肉8斤，明早送</div></div><div class="conversation"><div class="conversation-title"><span>江北食堂</span><small>11:48</small></div><div class="conversation-preview">白菜两筐，鸡蛋5板</div></div><div class="conversation"><div class="conversation-title"><span>万象城门店</span><small>昨天</small></div><div class="conversation-preview">昨天一样，饮料少一点</div></div></aside><main class="chat-main"><div class="chat-head"><b>天河鲜食店</b>${tag('在线','green')}</div><div class="messages"><div class="bubble">你好，我是 AI 订单助手，请发送订单文字、图片或文件。<div class="time">AI 助手 · 12:20</div></div><div class="bubble me">土豆20斤，前腿肉8斤，明早送<div class="time">王老板 · 12:26</div></div><div class="bubble">已识别 2 个商品，生成待审核订单 OT-20260714-0012。<div class="time">AI 助手 · 12:26</div></div></div><div class="composer"><textarea placeholder="输入订单内容，Enter 发送，Shift+Enter 换行"></textarea><div class="toolbar right">${btn('📎 上传文件','','data-action="toast" data-message="已选择文件（原型）"')}${btn('选择成员','','data-modal="memberPick"')}${btn('发送','primary','data-action="toast" data-message="消息已发送"')}</div></div></main><aside class="chat-info"><h3>识别结果</h3>${tag('待处理','orange')}<div class="review-card"><h4>天河鲜食店</h4><div class="card-body">土豆（黄心） × 20 斤<br><br>猪前腿肉 × 8 斤</div></div><a class="btn primary block" style="margin-top:14px" href="task-detail.html">进入审核</a><div class="divider"></div><h4>会话记忆</h4><p class="help">默认单位：斤<br>明早送 = 次日收货</p></aside></div>${modal('memberPick','选择模拟发送成员',`<div class="toolbar">${select(['王老板（客户）','李经理（工作人员）','AI 机器人'])}</div>`)}`;
add('chat-simulator.html','订单录入',shell('订单录入','/chat-simulator',chat),'.content{padding:0;overflow:hidden}.tabbar{display:none}');

// Customers
const customerRows=[
 ['<span class="mono">C10021</span>','<b>天河鲜食店</b>','广州市天河区体育西路 88 号','13800001111',tag('1 个群','blue'),'428','订单备注优先'],
 ['<span class="mono">C10037</span>','<b>江北食堂</b>','重庆市江北区观音桥 17 号','13600002222',tag('1 个群','blue'),'312','合并'],
 ['<span class="mono">C10052</span>','<b>万象城门店</b>','深圳市罗湖区宝安南路 1881 号','13900003333',tag('2 个群','blue'),'537','SPU备注优先'],
 ['<span class="mono">C10078</span>','<b>云岭酒店</b>','昆明市盘龙区白云路 9 号','13700004444','<span class="help">未绑定</span>','0','订单备注优先']
];
const customers=`<div class="page">${pageTitle('客户管理','查看客户资料、群绑定与已同步 SKU',`<div class="toolbar">${btn('同步全部客户','','data-action="toast" data-message="已触发全量同步"')}${btn('批量设置备注优先级','primary','data-modal="batchPriority"')}</div>`)}${card('',`<div class="toolbar"><input id="customerSearch" class="control search" placeholder="请输入名称、ID、地址或电话">${select(['全部绑定状态','已绑定','未绑定'])}${btn('查询','primary','data-filter="#customerSearch"')}${btn('重置','','onclick="location.reload()"')}</div>`)}${card('',table(['客户 ID','客户名称','地址','电话','群绑定','已同步的SKU数','备注优先级'],customerRows))}</div>${modal('batchPriority','批量设置备注优先级（已选 2 项）',`<div class="form-grid">${field('优先级',select(['订单备注优先','SPU备注优先','合并']),true,true)}${field('应用范围','<label><input type="radio" checked> 当前选中客户</label>　<label><input type="radio"> 筛选结果</label>',true)}</div>`)}`;
add('customers.html','客户管理',shell('客户管理','/customers',customers));

// Groups
const groupRows=[
 ['<a href="group-detail.html"><b>华南餐饮订货群</b></a>',tag('微信','blue'),'42','3 个客户','李娟','<button class="switch on"></button>','显示','06:00 - 22:00','<a class="btn link" href="group-detail.html">详情</a>'],
 ['<a href="group-detail.html"><b>江北食堂订货群</b></a>',tag('企业微信','blue'),'18','1 个客户','陈林','<button class="switch on"></button>','不显示','不限','<a class="btn link" href="group-detail.html">详情</a>'],
 ['<a href="group-detail.html"><b>客户订单邮箱</b></a>',tag('邮件','purple'),'—','1 个客户','王明','<button class="switch on"></button>','显示','不限','<button class="btn link" data-modal="emailGroup">编辑</button>'],
];
const groups=`<div class="page">${pageTitle('群聊管理','管理群聊客户绑定、审核员和接单规则',`<div class="toolbar">${btn('群聊迁移','','data-action="toast" data-message="已打开迁移向导"')}${btn('新增邮件群','primary','data-modal="emailGroup"')}</div>`)}${card('',`<div class="toolbar">${select(['全部类型','微信','企业微信','邮件'])}${select(['全部审核员','李娟','陈林','王明'])}<input id="groupSearch" class="control search" placeholder="搜索群聊名称">${btn('查询','primary','data-filter="#groupSearch"')}${btn('刷新','','data-action="toast" data-message="群聊数据已刷新"')}</div>`)}${card('',table(['群聊名称','类型','成员数','客户','审核员','发言','订单价格','下单时段','操作'],groupRows))}</div>${modal('emailGroup','新增邮件群',`<div class="form-grid">${field('名称',control('请输入名称'),true,true)}${field('发件人邮箱',control('customer@example.com'),true,true)}</div>`)}`;
add('groups.html','群聊管理',shell('群聊管理','/customers',groups));

const groupCustomers=table(['客户名称','客户 ID','操作'],[['天河鲜食店','<span class="mono">C10021</span>','<button class="btn link red" data-remove>删除</button>'],['云岭酒店','<span class="mono">C10078</span>','<button class="btn link red" data-remove>删除</button>']]);
const members=table(['昵称','微信号 (wxid)','类型','绑定客户'],[['王老板','wxid_wang001',select(['客户','工作人员']),'天河鲜食店'],['李经理','wxid_li002',select(['工作人员','客户']),'—'],['订单机器人','wxid_bot',tag('机器人','blue'),'—']]);
const splitRules=table(['序号','分类','目标门店','操作'],[['1','蔬菜 / 叶菜','天河鲜食店','<button class="btn link" data-modal="splitRule">编辑</button> <button class="btn link red" data-remove>删除</button>'],['2','肉禽 / 冻品','云岭酒店','<button class="btn link" data-modal="splitRule">编辑</button>']]);
const groupDetail=`<div class="page">${pageTitle('华南餐饮订货群','微信 · 42 位成员',`<a class="btn" href="groups.html">← 返回群聊</a>`)}${card('群聊设置',`<div class="form-grid">${field('群聊名称',control('华南餐饮订货群'))}${field('允许机器人发言','<button class="switch on"></button>')}${field('订单展示价格','<button class="switch on"></button>')}${field('下单时段','<div class="toolbar"><input class="control" type="time" value="06:00"><input class="control" type="time" value="22:00"></div>')}${field('可见审核员',select(['全部操作员','李娟','陈林','王明']),true)} </div><div class="toolbar right" style="margin-top:16px">${btn('保存设置','primary','data-action="toast" data-message="群聊设置已保存"')}</div>`)}${card('',tabs([['customers','客户列表',`<div class="toolbar right" style="margin-bottom:10px">${btn('管理客户','primary','data-modal="manageCustomers"')}</div>${groupCustomers}`],['members','群成员',`<div class="toolbar right" style="margin-bottom:10px">${btn('同步成员','','data-action="toast" data-message="成员已同步"')}</div>${members}`],['split','拆单设置',`<div class="toolbar right" style="margin-bottom:10px">${btn('增加拆单规则','primary','data-modal="splitRule"')}</div>${splitRules}`]]))}</div>${modal('manageCustomers','客户管理',`<div class="form-grid">${field('搜索客户',control('搜索客户名称或 ID'),true)}${field('待选客户','<label><input type="checkbox"> 江北食堂（C10037）</label><label><input type="checkbox"> 万象城门店（C10052）</label>',true)}${field('已选客户','<div>'+tag('天河鲜食店 ×','blue')+' '+tag('云岭酒店 ×','blue')+'</div>',true)}</div>`,true)}${modal('splitRule','增加拆单规则',`<div class="form-grid">${field('商品分类',select(['蔬菜 / 叶菜','肉禽 / 冻品','水产 / 海鲜']),true,true)}${field('目标门店',select(['默认继承父组客户','天河鲜食店','云岭酒店']),true)}${field('规则说明',control('选填'),true)}</div>`)}`;
add('group-detail.html','群聊详情',shell('群聊详情','/customers',groupDetail));

const customerGroups=`<div class="page">${pageTitle('客户分组','用于录单工作台按负责人聚合客户',btn('新建分组','primary','data-modal="groupEdit"'))}${card('',table(['分组名称','所有者','群聊','客户','操作'],[['重点客户组',select(['李娟','陈林','王明']),tag('4','blue'),tag('12','green'),'<button class="btn link" data-modal="groupEdit">编辑</button> <button class="btn link red" data-remove>删除</button>'],['普通客户组',select(['陈林','李娟','王明']),tag('8','blue'),tag('26','green'),'<button class="btn link" data-modal="groupEdit">编辑</button>'],['待分配',select(['选择所有者','李娟','陈林']),tag('2','blue'),tag('5','green'),'<button class="btn link" data-modal="groupEdit">编辑</button>']]))}</div>${modal('groupEdit','新建分组',`<div class="form-grid">${field('分组名称',control('请输入分组名称'),true,true)}${field('所有者',select(['请选择','李娟','陈林','王明']),true)}${field('关联群聊',select(['华南餐饮订货群','江北食堂订货群','直营门店补货群']),true)}${field('说明','<textarea class="control" placeholder="选填"></textarea>',true)}</div>`)}`;
add('customer-groups.html','客户分组',shell('客户分组','/customers',customerGroups));

// Quotation / SKU
const skuRows=[
 ['<span class="mono">SM-10021</span>','<b>华南餐饮标准报价单</b>','24','428','2026-07-14 09:30',tag('启用','green'),'<button class="btn link" data-modal="skuDetail">详情</button> <button class="btn link red" data-action="toast" data-message="已禁用">禁用</button>'],
 ['<span class="mono">SM-10037</span>','<b>江北食堂专用报价单</b>','8','312','2026-07-14 09:18',tag('启用','green'),'<button class="btn link" data-modal="skuDetail">详情</button>'],
 ['<span class="mono">SM-10052</span>','<b>直营门店零售报价单</b>','16','537','2026-07-13 23:40',tag('禁用','red'),'<button class="btn link" data-modal="skuDetail">详情</button>']
];
const skuDetailTabs=tabs([['products','商品',`<div class="toolbar" style="margin-bottom:12px">${control('搜索商品名...','search')}</div>${table(['SKU ID','商品名','单位','单价','状态'],[['SKU-28012','土豆（黄心）','斤 / 箱','¥2.80',tag('启用','green')],['SKU-39107','猪前腿肉','斤 / 件','¥15.60',tag('启用','green')],['SKU-10288','大白菜','斤 / 筐','¥1.90',tag('启用','green')]])}`],['customers','客户',`<div class="toolbar" style="margin-bottom:12px">${control('搜索客户名...','search')}</div>${table(['客户 ID','客户名称','报价单数','SKU 数'],[['C10021','天河鲜食店','2','428'],['C10078','云岭酒店','1','428']])}`]]);
const sku=`<div class="page">${pageTitle('报价单','同步并管理参与 AI 解析的报价单',`<div class="toolbar">${btn('同步选中报价单','primary','data-action="toast" data-message="同步任务已触发"')}${btn('刷新','','data-action="toast" data-message="列表已刷新"')}</div>`)}${metrics([['报价单总数','48'],['启用报价单','45','','green'],['SKU 总数','12,680','','blue'],['关联客户','326']],'four')}${card('',`<div class="toolbar"><input id="skuSearch" class="control search" placeholder="请输入名称搜索">${select(['全部状态','启用','禁用'])}${btn('查询','primary','data-filter="#skuSearch"')}${btn('重置','','onclick="location.reload()"')}</div>`)}${card('',table(['报价单 ID','报价单名称','关联客户','SKU 数量','同步时间','状态','操作'],skuRows))}</div>${modal('skuDetail','华南餐饮标准报价单 — 详情',skuDetailTabs,true)}`;
add('sku.html','报价单',shell('报价单','/sku',sku));

// Prompt and memory
const promptRows=[
 ['<b>天河店生鲜订单规则</b>',tag('订单解析','blue'),'天河鲜食店',tag('启用','green'),'<span class="mono"># 商品别名\n小番茄 → 圣女果…</span>','07-14 10:22','<button class="btn link" data-modal="promptEdit">编辑</button> <button class="btn link red" data-remove>删除</button>'],
 ['<b>食堂意图判断规则</b>',tag('意图识别','purple'),'江北食堂',tag('启用','green'),'<span class="mono">“对账”识别为 other…</span>','07-13 19:08','<button class="btn link" data-modal="promptEdit">编辑</button>'],
 ['<b>全局默认解析规则</b>',tag('订单解析','blue'),'全部客户',tag('停用','red'),'<span class="mono">默认单位按报价单…</span>','07-10 11:32','<button class="btn link" data-modal="promptEdit">查看</button>']
];
const systemPrompt=`<div class="grid two">${card('系统提示词',`<textarea class="control" style="min-height:330px" placeholder="# 系统提示词\n用于补充商户级的商品别名、品类术语和特殊规则"># 商品别名\n- 小番茄 / 千禧果 → 圣女果\n- 大白 → 大白菜\n\n# 品类术语\n- “件”代表整箱包装</textarea><div class="toolbar right" style="margin-top:12px">${btn('恢复默认')}${btn('保存','primary','data-action="toast" data-message="系统提示词已保存"')}</div>`)}${card('意图识别补充规则',`<textarea class="control" style="min-height:330px">- “对账”/“结算单”/“开票”统一识别为 other\n- “排菜单”识别为 order\n- 无可解析文本的语音/视频归为 inquiry</textarea><div class="toolbar right" style="margin-top:12px">${btn('恢复默认')}${btn('保存','primary','data-action="toast" data-message="意图规则已保存"')}</div>`)}</div>`;
const prompts=`<div class="page">${pageTitle('提示词','配置客户专属规则与系统级 AI 指令')}${card('',tabs([['customer','客户提示词',`<div class="toolbar" style="margin-bottom:12px"><input id="promptSearch" class="control search" placeholder="搜索客户名称或 ID">${select(['全部类型','订单解析','意图识别'])}${btn('导入模版','','data-modal="presetImport"')}${btn('AI 预识别','','data-modal="aiGenerate"')}${btn('新建模板','primary','data-modal="promptEdit"')}</div>${table(['模板名称','类型','绑定客户','状态','Prompt 预览','更新时间','操作'],promptRows)}`],['system','系统提示词',systemPrompt]]))}</div>${modal('promptEdit','新建提示词模板',`<div class="form-grid">${field('模板名称',control('例如：李总-生鲜订单格式'),true,true)}${field('模板类型',select(['订单解析（文本/图片识别）','意图识别（判断消息是否订单）']),false,true)}${field('启用状态','<button class="switch on"></button>')}${field('按群聊绑定',select(['不按群聊','华南餐饮订货群（3个客户）','江北食堂订货群（1个客户）']),true)}${field('绑定客户',select(['留空 = 全部客户','天河鲜食店','江北食堂','万象城门店']),true)}${field('Prompt 内容','<textarea class="control" style="min-height:190px" placeholder="# 该客户特殊规则\n1. “大白”指“大白菜”\n2. 数量单位默认为“斤”"></textarea>',true,true)}</div>`,true)}${modal('presetImport','从模版库导入',`<div class="toolbar" style="margin-bottom:12px">${control('搜索名称、描述、分类','search')}${select(['全部分类','商品别名','意图规则','单位换算'])}</div>${table(['模版名称','分类','描述','内容预览','操作'],[['生鲜常用别名',tag('商品别名','blue'),'蔬菜行业常用称呼','小番茄→圣女果…','<button class="btn link" data-save>导入</button>'],['非订单意图规则',tag('意图规则','purple'),'对账、开票等场景','对账→other…','<button class="btn link" data-save>导入</button>']])}`,true)}${modal('aiGenerate','AI 预识别',`<div class="form-grid">${field('原始订单样本','<textarea class="control" placeholder="粘贴 3-10 条历史订单样本"></textarea>',true,true)}${field('绑定客户',select(['天河鲜食店','江北食堂']),true)}${field('生成类型',select(['订单解析提示词','意图识别提示词']),true)}</div>`)}`;
add('prompts.html','提示词',shell('提示词','/prompts',prompts));

const correctionTable=table(['客户原始输入','修正为','命中次数','操作'],[['前腿','猪前腿肉（斤）','12','<button class="btn link red" data-remove>删除</button>'],['大白','大白菜（斤）','8','<button class="btn link red" data-remove>删除</button>'],['小番茄','圣女果（斤）','5','<button class="btn link red" data-remove>删除</button>']]);
const habitTable=table(['SKU','类型','单位','换算','备注模板','操作'],[['土豆（SKU-28012）',tag('仅备注'),'斤 → 斤','—','“明早送”','<button class="btn link red" data-remove>删除</button>'],['鸡蛋（SKU-18920）',tag('倍率','green'),'板 → 个','× 30','—','<button class="btn link red" data-remove>删除</button>'],['饮用水（SKU-81201）',tag('占位','orange'),'件 → 瓶','= 24','整件','<button class="btn link red" data-remove>删除</button>']]);
const memory=`<div class="page">${pageTitle('AI 记忆','查看和维护由人工纠错沉淀的长期记忆')}${card('',tabs([['customer','客户记忆',`<div class="toolbar" style="margin-bottom:12px">${select(['天河鲜食店','江北食堂','万象城门店'])}${select(['全部记忆类型','修正记忆','下单习惯'])}${btn('新增记忆','primary','data-modal="memoryEdit"')}</div>${tabs([['correction','修正记忆',correctionTable],['habit','下单习惯',habitTable]])}`],['group','群聊记忆',`<div class="toolbar" style="margin-bottom:12px">${select(['华南餐饮订货群','江北食堂订货群'])}${btn('新增群记忆','primary','data-modal="memoryEdit"')}</div>${table(['记忆类型','内容','来源','更新时间','操作'],[[tag('群级规则','purple'),'群内“明早”统一按次日收货','人工配置','07-12 16:40','<button class="btn link" data-modal="memoryEdit">编辑</button>'],[tag('群成员','blue'),'王老板绑定天河鲜食店','群同步','07-14 09:30','<button class="btn link">查看</button>']])}`]]))}</div>${modal('memoryEdit','新增 AI 记忆',`<div class="form-grid">${field('记忆类型',select(['修正记忆','下单习惯','群级规则']),true,true)}${field('客户 / 群聊',select(['天河鲜食店','华南餐饮订货群']),true,true)}${field('原始称呼',control('例如：前腿'))}${field('标准商品',control('搜索 SKU'))}${field('单位换算',select(['仅备注','倍率','固定占位']))}${field('记忆内容','<textarea class="control" placeholder="请输入规则描述"></textarea>',true,true)}</div>`)}`;
add('memory.html','AI 记忆',shell('AI 记忆','/prompts',memory));

// Stats and decision dashboards
const auditorTable=table(['#','审核员','下单客户数','提交订单数','下单商品数'],[['<span class="rank top">1</span>','<b>李娟</b>','18','46','236'],['<span class="rank">2</span>','<b>陈林</b>','15','39','202'],['<span class="rank">3</span>','<b>王明</b>','12','31','168']]);
const quotaContent=`${metrics([['总额度','12,000'],['已使用','3,358','','orange'],['剩余额度','8,642','','blue'],['本月消耗','1,286']],'four')}${card('额度使用趋势',chart())}${card('额度变更记录',table(['时间','类型','变更额度','余额','备注'],[['07-01 09:30',tag('充值','green'),'+ 5,000','9,802','季度充值'],['07-14 12:26',tag('扣减','red'),'- 2','8,642','订单提交 OT-0012']]))}`;
const stats=`<div class="page">${pageTitle('统计','审核绩效与录单额度使用情况')}${card('',tabs([['auditor','审核员绩效',`<div class="toolbar" style="margin-bottom:12px">${select(['今日','昨日','本周','本月','上月'])}<input class="control" type="date" value="2026-07-14"><input class="control" type="date" value="2026-07-14">${btn('查询','primary')}</div>${auditorTable}`],['quota','录单额度',quotaContent]]))}</div>`;
add('stats.html','统计',shell('统计','/stats',stats));

const decisionSections=`<div class="section-title"><b>01</b><h2>核心指标概览</h2><span>— 资产、经营与降本视角</span></div>${card('AI 额度资产与消耗',metrics([['剩余可用条数','8,642','','blue'],['累计充值总额度','12,000'],['本期提交总条数','1,286'],['本期已消耗条数','1,240','','red']],'four'))}${metrics([['累计节省工时','3.8 人/日','≈ 全职接单员','green'],['商品识别率','96.8%','字段 + 单位 + 数量','blue'],['活跃群占比','18 / 22','下单群 / 绑定群'],['订单提交数','286 / 302','提交 / 生成'],['新增记忆数','42','纠错 + 习惯','blue']],'five')}<div class="section-title"><b>02</b><h2>多模态分析与趋势</h2><span>— 算法表现视角</span></div>${card('多模态下单类型分析',metrics([['纯文本下单','218','准确率 98.2%','blue'],['图片下单','56','准确率 93.6%','orange'],['文件下单','24','准确率 95.1%','green'],['其他类型','4','准确率 88.0%']],'four'))}<div class="grid two">${card('AI 录单数走势',chart())}${card('综合准确率与记忆成长曲线',chart('#52c41a'))}</div><div class="section-title"><b>03</b><h2>异常诊断</h2><span>— 业务排雷视角</span></div><div class="grid two">${card('商品 SKU 纠错榜 Top 5',table(['排名','系统基准商品','客户实际称呼','纠错次数'],[['1','猪前腿肉','前腿','12'],['2','大白菜','大白','8'],['3','圣女果','小番茄','5']]))}${card('错误订单 Top 5',table(['订单编码','下单类型','门店','人工修改/总提交'],[['OT-0012',tag('文本','blue'),'天河鲜食店','2 / 8'],['OT-0008',tag('图片','orange'),'江北食堂','3 / 12']]))}</div><div class="section-title"><b>04</b><h2>审核员效能</h2><span>— 内部管理视角</span></div>${card('审核员效能统计',table(['接单员','审核订单','提交订单','负责群数','人工纠错','识别率','平均停留','状态'],[['李娟','46','44','8','12','96.8%','38 秒',tag('正常','green')],['陈林','39','37','7','9','95.4%','31 秒',tag('正常','green')],['王明','31','28','5','14','91.2%','0.8 秒',tag('盲审预警','red')]]))}`;
const decision=`<div class="page">${pageTitle('经营决策大屏','从单纯看明细到看诊断与管资产 · 一屏总览 AI 商业价值',`<div class="toolbar"><span class="help">时间范围</span>${select(['今日实时','昨日','近 7 天','近 30 天','自定义'])}</div>`)}${decisionSections}</div>`;
add('decision-dashboard.html','经营决策大屏',shell('决策大屏','/decision-dashboard',decision));
add('daily-report.html','经营决策日报',`<main class="report" style="padding:20px"><section class="report-hero"><h1>经营决策大屏</h1><p>观麦演示租户 · 2026-07-14 · 从单纯看明细到看诊断与管资产</p><div class="toolbar">${select(['今日','昨日','近7天','近30天','自定义'])}<input class="control" type="date" value="2026-07-14"></div></section>${decisionSections}</main>`);

// Settings
const operatorTable=table(['用户名','姓名','角色','状态','操作'],[['wangming','王明',tag('管理员','blue'),tag('启用','green'),'<button class="btn link" data-modal="passwordEdit">修改密码</button>'],['lijuan','李娟',tag('操作员'),tag('启用','green'),'<button class="btn link" data-modal="passwordEdit">修改密码</button> <button class="btn link red" data-remove>删除</button>'],['chenlin','陈林',tag('操作员'),tag('启用','green'),'<button class="btn link">转让管理员</button>']]);
const channelTable=table(['名称','类型','状态','操作'],[['华南微信机器人',tag('微信','blue'),tag('在线','green'),'<a class="btn link" href="settings-channel-detail.html">详情</a>'],['企业微信助手',tag('企业微信','blue'),tag('在线','green'),'<a class="btn link" href="settings-channel-detail.html">详情</a>'],['订单接收邮箱',tag('邮件','purple'),tag('停用','red'),'<a class="btn link" href="settings-channel-detail.html">详情</a>']]);
const notificationSettings=`<div class="form-grid">${field('每日经营播报','<button class="switch on"></button>')}${field('播报时间','<input class="control" type="time" value="08:30">')}${field('失败订单通知','<button class="switch on"></button>')}${field('额度不足通知','<button class="switch on"></button>')}${field('通知群聊',select(['平台通知群','华南餐饮订货群']),true)}${field('低额度阈值','<input class="control" type="number" value="500">',true)} </div><div class="toolbar right" style="margin-top:16px">${btn('保存通知设置','primary','data-action="toast" data-message="通知设置已保存"')}</div>`;
const settings=`<div class="page">${pageTitle('设置','成员、信道、回复与通知配置')}${card('',tabs([['operators','成员管理',`<div class="toolbar right" style="margin-bottom:12px">${btn('新增成员','primary','data-modal="operatorEdit"')}</div>${operatorTable}`],['channels','信道设置',`<div class="toolbar right" style="margin-bottom:12px">${btn('刷新','','data-action="toast" data-message="信道状态已刷新"')}</div>${channelTable}`],['replies','回复设置',`<div class="alert">配置机器人在识别、确认和失败等场景下的回复文案。</div><a class="btn primary" href="settings-replies.html">进入回复设置</a>`],['notifications','通知设置',notificationSettings]]))}</div>${modal('operatorEdit','新增成员',`<div class="form-grid">${field('姓名',control('请输入姓名'),true,true)}${field('用户名',control('请输入用户名'),true,true)}${field('密码','<input class="control" type="password" placeholder="至少 6 个字符">',true,true)}</div>`)}${modal('passwordEdit','修改密码',`<div class="form-grid">${field('新密码','<input class="control" type="password" placeholder="请输入新密码">',true,true)}${field('确认密码','<input class="control" type="password" placeholder="请再次输入新密码">',true,true)}</div>`)}`;
add('settings.html','设置',shell('设置','/settings',settings));

const replyScenarios=[['orderReceived','收到订单','已收到您的订单，正在为您识别商品信息。'],['orderCreated','识别完成','订单已识别完成，共 {{item_count}} 个商品，请稍候审核。'],['orderSubmitted','提交成功','订单 {{order_no}} 已成功提交，感谢您的下单。'],['orderFailed','识别失败','抱歉，本次订单未能识别，请补充商品名称和数量。']];
const replies=`<div class="page">${pageTitle('回复设置','配置不同业务场景下的机器人回复文案',`<a class="btn" href="settings.html">← 返回设置</a>`)}<div class="alert warn">建议开启自定义回复并添加 3-5 条不同文案，系统会随机选择一条发送，避免重复内容。</div>${replyScenarios.map(([id,t,v],i)=>card(t,`<div class="form-grid">${field('启用回复',`<button class="switch ${i<3?'on':''}"></button>`)}${field('显示商品明细','<button class="switch on"></button>')}${field('自定义回复文案',`<input class="control" value="${v}"><input class="control" style="margin-top:8px" placeholder="自定义回复文案">`,true)}<div class="field full"><div class="toolbar">${btn('＋ 添加一条','dashed','data-action="toast" data-message="已添加文案输入框"')}${btn('恢复默认','small','data-action="toast" data-message="已恢复默认文案"')}</div></div></div>`)).join('')}<div class="toolbar right">${btn('保存全部设置','primary','data-action="toast" data-message="回复设置已保存"')}</div></div>`;
add('settings-replies.html','回复设置',shell('回复设置','/settings',replies));

const channelDetail=`<div class="page">${pageTitle('华南微信机器人','信道详情与连接状态',`<a class="btn" href="settings.html">← 返回设置</a>`)}${metrics([['连接状态','在线','','green'],['信道类型','微信'],['绑定群聊','12','','blue'],['今日消息','328']],'four')}${card('基础信息',`<div class="form-grid">${field('信道 ID','<span class="mono">CH-WX-10021</span>')}${field('信道名称',control('华南微信机器人'))}${field('启用','<button class="switch on"></button>')}${field('最近心跳','2026-07-14 12:40:06')}${field('AccessKey',control('AK••••••••••921'))}${field('RobotKey',control('RK••••••••••416'))}</div><div class="toolbar right" style="margin-top:16px">${btn('保存','primary','data-action="toast" data-message="信道设置已保存"')}</div>`)}${card('绑定群聊',table(['群聊名称','成员数','机器人禁言','同步时间'],[['华南餐饮订货群','42','否','07-14 09:30'],['直营门店补货群','63','否','07-14 09:30']]))}</div>`;
add('settings-channel-detail.html','信道详情',shell('信道详情','/settings',channelDetail));

// Embed routes
add('embed.html','嵌入入口',`<div style="min-height:100vh;display:grid;place-items:center;background:#f5f5f5"><div class="card" style="padding:48px;text-align:center;width:520px"><div style="font-size:52px;color:#faad14">⚠</div><h2>缺少入口凭证</h2><p class="help">请从系统内重新打开</p><a class="btn primary" href="embed-test.html">前往嵌入链路联调</a></div></div>`);
const embedTest=`<div style="min-height:100vh;background:#f5f5f5;padding:18px"><div class="grid two" style="grid-template-columns:360px 1fr;height:calc(100vh - 36px)"><section class="card"><div class="card-head">嵌入链路联调</div><div class="card-body"><p class="help">模拟宿主平台：服务端签名 → 颁发一次性 ticket → iframe 加载 /embed。</p><div class="form-grid" style="grid-template-columns:1fr">${field('station_id（租户唯一键）',control('如 T43206'),false,true)}${field('username（成员唯一键）',control('如 embed_user1'),false,true)}${field('nickname（可选，成员显示名）',control('如 王小明'))}${field('group_id（可选，附属信息）',control('如 G10001'))}</div>${btn('生成 ticket 并加载 iframe','primary block','data-action="toast" data-message="ticket 已颁发（60s 有效 · 一次性）"')}<div class="alert" style="margin-top:14px">ticket 已颁发（60s 有效 · 一次性）</div><div class="help">验证一次性：复制 ticket，第二次访问应失败。</div></div></section><section class="card" style="overflow:hidden"><div class="card-head">embed</div><iframe title="embed" src="chat-simulator.html" style="border:0;width:100%;height:calc(100% - 46px)"></iframe></section></div></div>`;
add('embed-test.html','嵌入链路联调',embedTest);

// Platform administrator pages
const tenantRows=[
 ['<b>观麦演示租户</b><div class="mono">M-10021</div>',tag('正式','green'),select(['V2','V1']),'<span class="mono">T43206</span>','G-8821','共享','平台通知群','王明','张销售','李 CSM','8,642 / 12,000','¥36,000','¥24,000',tag('推广上线中','cyan'),'07-01','07-31','<button class="btn link" data-modal="tenantEdit">编辑</button> <button class="btn link" data-action="toast" data-message="更多操作菜单">更多</button>'],
 ['<b>江北餐饮配送</b><div class="mono">M-10037</div>',tag('试用','blue'),select(['V2','V1']),'<span class="mono">T43237</span>','G-9012','私有','江北通知群','陈总','赵销售','周 CSM','386 / 500','¥8,000','¥4,000',tag('试用中','blue'),'07-10','07-24','<button class="btn link" data-modal="tenantEdit">编辑</button> <button class="btn link">更多</button>'],
 ['<b>云岭酒店供应链</b><div class="mono">M-10052</div>',tag('测试'),'V1','—','—','共享','—','—','钱销售','李 CSM','0 / 100','¥0','¥0',tag('测试中','orange'),'07-12','07-26','<button class="btn link" data-modal="tenantEdit">编辑</button>']
];
const merchantTab=`${card('租户列表',`<div class="toolbar" style="margin-bottom:12px">${select(['使用阶段','已禁用','试用中','测试中','推广上线中','全面上线','已下线'])}${select(['信道','共享','私有'])}${select(['对接平台','老架构(GM)','新架构(Ceres)','第三方系统'])}${select(['类型','试用','正式','测试','已过期','嵌入式试用'])}${select(['回款','全回款','部分回款','未回款'])}${select(['录单版本','V1','V2'])}<input id="tenantSearch" class="control search" placeholder="搜索 名称 / ID / Station / Group">${btn('新建租户','primary','data-modal="tenantEdit"')}</div>${table(['租户','类型','录单版本','Station','Group','信道类型','通知群','管理员','销售','CSM','额度','总合同金额','总回款金额','使用阶段','试用开始','试用结束','操作'],tenantRows)}`)}`;
const subscriptionRows=[['观麦演示租户','12,000','3,358','8,642','28%',tag('正常','green'),'<button class="btn link" data-modal="recharge">充值</button> <button class="btn link">扣减</button> <button class="btn link">记录</button>'],['江北餐饮配送','500','114','386','23%',tag('正常','green'),'<button class="btn link" data-modal="recharge">充值</button>'],['云岭酒店供应链','100','100','0','100%',tag('已耗尽','red'),'<button class="btn link" data-modal="recharge">充值</button>']];
const subscriptionTab=`${card('额度管理',`<div class="toolbar" style="margin-bottom:12px">${control('搜索租户名 / ID / 管理员','search')}${btn('查询','primary')}</div>${table(['租户','总额度','已用','剩余','使用率','状态','操作'],subscriptionRows)}`)}`;
const contractRows=[['<span class="mono">CT-20260701</span>','观麦演示租户',tag('充值','blue'),'2026-07-01','¥36,000','¥24,000','¥0','张销售',tag('部分回款','orange'),'<button class="btn link" data-modal="contractEdit">编辑</button>'],['<span class="mono">CT-20260710</span>','江北餐饮配送',tag('试用'),'2026-07-10','¥8,000','¥4,000','¥0','赵销售',tag('部分回款','orange'),'<button class="btn link" data-modal="contractEdit">编辑</button>']];
const contractTab=`${metrics([['合同总额','¥44,000'],['已回款','¥28,000','','green'],['未回款','¥16,000','','orange'],['合同数量','2']],'four')}${card('合同列表',`<div class="toolbar" style="margin-bottom:12px">${select(['全部合同类型','试用','充值','定制'])}${select(['全部回款状态','已回款','部分回款','未回款'])}${control('搜索租户或合同编号','search')}${btn('新增合同','primary','data-modal="contractEdit"')}</div>${table(['合同编号','租户','合同类型','签约时间','金额','已收','退款','销售人员','状态','操作'],contractRows)}`)}`;
const adminDashboard=`${metrics([['租户总数','128'],['试用中','18','','blue'],['全面上线','72','','green'],['本月合同额','¥286,000','','orange']],'four')}<div class="grid two">${card('租户增长趋势',chart())}${card('额度消耗趋势',chart('#52c41a'))}</div>${card('待跟进租户',table(['租户','阶段','剩余额度','试用结束','负责人'],[['江北餐饮配送',tag('试用中','blue'),'386','07-24','赵销售'],['云岭酒店供应链',tag('测试中','orange'),'0','07-26','钱销售']]))}`;
const tenantTabs=tabs([['merchants','▣ 租户管理',merchantTab],['subscription','◇ 额度管理',subscriptionTab],['contracts','▤ 合同管理',contractTab],['dashboard','◉ 数据看板',adminDashboard]]);
const adminTenants=`<div class="page">${pageTitle('租户管理','平台租户、额度、合同与经营数据统一管理')}${tenantTabs}</div>${modal('tenantEdit','新建 / 编辑租户',`<div class="form-grid">${field('租户名称',control('请输入租户名称'),false,true)}${field('租户类型',select(['试用','正式','测试','嵌入式试用']),false,true)}${field('对接平台',select(['老架构(GM)','新架构(Ceres)','第三方系统']),false,true)}${field('信道模式',select(['共享','私有']),false,true)}${field('Station ID',control('如 T43206'))}${field('Group ID',control('如 G8821'))}${field('管理员用户名',control('admin'),false,true)}${field('管理员姓名',control('显示名称'),false,true)}${field('联系人',control('姓名'))}${field('联系电话',control('手机号'))}${field('销售',control('销售人员'))}${field('CSM',control('客户成功经理'))}${field('实施',control('实施负责人'))}${field('试用周期','<div class="toolbar"><input class="control" type="date"><input class="control" type="date"></div>',true)}</div>`,true)}${modal('recharge','额度充值',`<div class="form-grid">${field('充值额度','<input class="control" type="number" placeholder="如：500">',false,true)}${field('赠送额度','<input class="control" type="number" placeholder="如：100">')}${field('关联合同',select(['不关联','2026-07-01 · ¥36,000 · RECHARGE']),true)}${field('充值备注','<textarea class="control"></textarea>',true)}</div>`)}${modal('contractEdit','新增 / 编辑合同',`<div class="form-grid">${field('租户',select(['观麦演示租户','江北餐饮配送']),false,true)}${field('合同类型',select(['试用','充值','定制']),false,true)}${field('签约时间','<input class="control" type="date">',false,true)}${field('金额(元)','<input class="control" type="number" value="0">',false,true)}${field('已收(元)','<input class="control" type="number" value="0">')}${field('退款(元)','<input class="control" type="number" value="0">')}${field('销售人员',control('姓名'))}${field('合同备注','<textarea class="control"></textarea>',true)}</div>`)}`;
add('admin-tenants.html','租户管理',shell('租户管理','/admin/tenants',adminTenants,{admin:true}));
add('admin.html','平台管理',shell('租户管理','/admin/tenants',adminTenants,{admin:true}));

const admins=`<div class="page">${pageTitle('系统管理员','管理平台级管理员账号',btn('新增系统管理员','primary','data-modal="superAdminEdit"'))}${card('',table(['用户名','姓名','角色','状态','最后登录','创建时间','操作'],[['root','平台所有者',tag('OWNER','purple'),tag('启用','green'),'07-14 12:02','2026-01-01','<button class="btn link" data-modal="superAdminEdit">编辑</button>'],['ops_admin','运营管理员',tag('SUPER_ADMIN','blue'),tag('启用','green'),'07-14 09:46','2026-03-18','<button class="btn link" data-modal="superAdminEdit">编辑</button> <button class="btn link red" data-remove>删除</button>']]))}</div>${modal('superAdminEdit','新增系统管理员',`<div class="form-grid">${field('用户名',control('请输入用户名'),true,true)}${field('姓名',control('请输入姓名'),true,true)}${field('密码','<input class="control" type="password" placeholder="至少 6 个字符">',true,true)}${field('角色',select(['SUPER_ADMIN','OWNER']),true,true)}${field('启用','<button class="switch on"></button>',true)}</div>`)}`;
add('admin-system-admins.html','系统管理员',shell('系统管理员','/admin/system-admins',admins,{admin:true}));

const presetRows=[['<b>生鲜常用商品别名</b>',tag('通用规则','green'),tag('商品别名','blue'),'蔬菜行业常见简称与别名','小番茄 → 圣女果；大白 → 大白菜…','07-12 10:18','<button class="btn link" data-modal="presetEdit">编辑</button> <button class="btn link red" data-remove>删除</button>'],['<b>非订单意图识别</b>',tag('预识别指令','blue'),tag('意图规则','purple'),'对账、开票等非订单场景','对账/结算单/开票 → other…','07-10 17:20','<button class="btn link" data-modal="presetEdit">编辑</button>']];
const presets=`<div class="page">${pageTitle('模版库','维护可供租户导入的提示词模版',btn('新建模版','primary','data-modal="presetEdit"'))}${card('',`<div class="toolbar" style="margin-bottom:12px">${select(['全部类型','通用规则','预识别指令'])}${select(['全部分类','商品别名','意图规则','单位换算'])}${control('搜索模版名称或描述','search')}${btn('查询','primary')}</div>${table(['模版名称','类型','分类','描述','内容预览','更新时间','操作'],presetRows)}`)}</div>${modal('presetEdit','新建模版',`<div class="form-grid">${field('模版名称',control('例如：供应商过滤-排除XX供应商'),true,true)}${field('模版类型',select(['通用规则','预识别指令']),true,true)}${field('分类',control('选择或输入分类'),true,true)}${field('描述',control('简要描述适用场景'),true)}${field('内容','<textarea class="control" style="min-height:220px" placeholder="请输入模版内容"></textarea>',true,true)}</div>`,true)}`;
add('admin-presets.html','模版库',shell('模版库','/admin/presets',presets,{admin:true}));

const adminStatsMain=`${metrics([['活跃租户','96'],['提交订单','28,642','','blue'],['商品行数','182,306'],['平均识别率','95.7%','','green']],'four')}<div class="grid two">${card('订单量趋势',chart())}${card('识别率趋势',chart('#52c41a'))}</div>${card('租户数据排名',table(['排名','租户','提交订单','商品行数','识别率'],[['1','观麦演示租户','2,862','18,230','96.8%'],['2','江北餐饮配送','2,406','16,980','95.4%']]))}`;
const accuracy=`<div class="toolbar" style="margin-bottom:12px">${select(['近 7 天','近 30 天','本月'])}${select(['全部租户','观麦演示租户','江北餐饮配送'])}${select(['全部消息类型','纯文本','图片','文件'])}${btn('查询','primary')}</div>${table(['订单编码','租户','消息类型','门店','商品数','正确数','人工修改','识别率','操作'],[['<a href="admin-stats-case.html">OT-20260714-0012</a>','观麦演示租户',tag('文本','blue'),'天河鲜食店','8','6','2','75%','<a class="btn link" href="admin-stats-case.html">案例详情</a>'],['<a href="admin-stats-case.html">OT-20260714-0008</a>','江北餐饮配送',tag('图片','orange'),'江北食堂','12','9','3','75%','<a class="btn link" href="admin-stats-case.html">案例详情</a>']] )}`;
const token=`${metrics([['活跃租户数','96'],['总 Token 数 (M)','128.6'],['Prompt Tokens (M)','92.4'],['Completion Tokens (M)','36.2'],['调用次数','286,420']],'five')}${card('租户排行',table(['#','租户','总 Token 数 (M)','Prompt Tokens (M)','Completion Tokens (M)','调用次数','提交订单数','商品行数','每行 Token'],[['1','观麦演示租户','12.86','9.24','3.62','28,642','2,862','18,230','706'],['2','江北餐饮配送','10.42','7.31','3.11','22,406','2,406','16,980','614']]))}`;
const adminStats=`<div class="page">${pageTitle('统计分析','平台全局数据、案例准确率与 Token 用量')}${card('',tabs([['stats','▥ 统计',adminStatsMain],['accuracy','⚗ 案例分析',accuracy],['tokens','⚡ Token 用量',token]]))}</div>`;
add('admin-stats.html','统计分析',shell('统计分析','/admin/stats',adminStats,{admin:true}));

const casePage=`<div class="page">${pageTitle('案例分析详情','OT-20260714-0012 · 观麦演示租户',`<a class="btn" href="admin-stats.html">← 返回案例列表</a>`)}${metrics([['商品总数','8'],['识别正确','6','','green'],['人工修正','2','','orange'],['识别率','75%','','red']],'four')}<div class="grid two">${card('原始信息',`<div class="alert">土豆20斤，前腿肉8斤，明早送天河店。西红柿三箱，鸡蛋五板。</div>${table(['AI 原始商品','识别 SKU','单位','数量'],[['土豆','土豆（黄心）','斤','20'],['前腿肉','五花肉','斤','8'],['西红柿','番茄','箱','3']])}`)}${card('人工修正',`${table(['客户输入','AI 结果','人工结果','变化'],[['前腿肉','五花肉','猪前腿肉',tag('SKU 修正','orange')],['西红柿','番茄','西红柿',tag('名称修正','orange')]])}<button class="btn primary" style="margin-top:12px" data-modal="caseMemory">查看客户记忆</button>`)}</div>${card('处理链路',table(['阶段','模型 / 组件','耗时','Token','结果'],[['意图识别','gpt-4.1-mini','0.42s','386',tag('order','green')],['订单解析','gpt-4.1','2.18s','2,840',tag('8 items','blue')],['SKU 重排','reranker-v2','0.31s','—',tag('完成','green')]]))}</div>${modal('caseMemory','天河鲜食店（C10021）- 客户记忆',correctionTable,true)}`;
add('admin-stats-case.html','案例分析详情',shell('案例详情','/admin/stats',casePage,{admin:true}));

const channelAdminRows=[['<b>平台共享微信信道</b><div class="mono">CH-SHARED-WX</div>',tag('微信','blue'),tag('在线','green'),'<button class="switch on"></button>','<button class="btn link" data-modal="channelAdminEdit">查看</button> <button class="btn link" data-modal="channelAdminEdit">编辑</button>'],['<b>企业微信主信道</b><div class="mono">CH-WW-001</div>',tag('企业微信','blue'),tag('在线','green'),'<button class="switch on"></button>','<button class="btn link" data-modal="channelAdminEdit">编辑</button>'],['<b>订单接收邮箱 / orders@shop.com</b><div class="mono">CH-EMAIL-001</div>',tag('邮件','purple'),tag('停用','red'),'<button class="switch"></button>','<button class="btn link" data-modal="channelAdminEdit">编辑</button>']];
const channelAdmin=`${card('信道列表',`<div class="toolbar right" style="margin-bottom:12px">${btn('导出全部群聊')}${btn('新建信道','primary','data-modal="channelAdminEdit"')}</div>${table(['名称','类型','状态','启用','操作'],channelAdminRows)}`)}`;
const providers=`${card('模型供应商',`<div class="toolbar" style="justify-content:space-between;margin-bottom:12px"><span class="help">配置 OpenAI 兼容的模型服务凭据，供按群模型配置选用</span>${btn('新建供应商','primary','data-modal="providerEdit"')}</div>${table(['名称','Base URL','API Key','模型','创建时间','操作'],[['OpenAI 官方','https://api.openai.com/v1','sk-••••••921','gpt-4.1, gpt-4.1-mini','2026-04-12','<button class="btn link" data-modal="providerEdit">编辑</button> <button class="btn link red" data-remove>删除</button>'],['DeepSeek 官方','https://api.deepseek.com/v1','sk-••••••286','deepseek-chat, deepseek-reasoner','2026-05-18','<button class="btn link" data-modal="providerEdit">编辑</button>']])}`)}`;
const bridges=`${card('Bridge 管理',`<div class="toolbar right" style="margin-bottom:12px">${btn('新建 Bridge','primary','data-modal="bridgeEdit"')}</div>${table(['名称','API Key','环境','启用','来源信道','群聊数量','过期时间','创建时间','操作'],[['合作方 A','<span class="mono">br_••••921</span>',tag('生产','green'),'<button class="switch on"></button>','平台共享微信信道','18','永不过期','2026-06-01','<button class="btn link" data-modal="bridgeEdit">编辑</button> <button class="btn link">群聊</button>'],['测试桥接','<span class="mono">br_••••286</span>',tag('预发布','orange'),'<button class="switch on"></button>','企业微信主信道','4','2026-08-01','2026-07-01','<button class="btn link" data-modal="bridgeEdit">编辑</button>']])}`)}`;
const adminSystem=`<div class="page">${pageTitle('系统设置','平台信道、模型供应商与桥接管理')}${card('',tabs([['channels','◉ 信道管理',channelAdmin],['providers','◇ 模型供应商',providers],['bridges','⌘ 桥接管理',bridges]]))}</div>${modal('channelAdminEdit','新建 / 编辑信道',`<div class="form-grid">${field('类型',select(['微信','企业微信','邮件','SaaS Bridge']),false,true)}${field('名称',control('如：张三的机器人'),false,true)}${field('启用','<button class="switch on"></button>')}${field('AccessKey',control('AccessKey'),false,true)}${field('AccessSecret','<input class="control" type="password">',false,true)}${field('RobotKey',control('RobotKey'),false,true)}${field('回调验签密钥（可选）',control('可选'),true)}</div>`,true)}${modal('providerEdit','新建 / 编辑供应商',`<div class="form-grid">${field('名称',control('如：DeepSeek 官方'),true,true)}${field('Base URL',control('https://api.deepseek.com/v1'),true,true)}${field('API Key','<input class="control" type="password" placeholder="sk-...">',true,true)}${field('模型列表',control('如：deepseek-chat、deepseek-reasoner'),true,true)}</div>`)}${modal('bridgeEdit','新建 / 编辑 Bridge',`<div class="form-grid">${field('名称',control('如：某合作方桥接'),true,true)}${field('环境',select(['开发','预发布','生产']),true,true)}${field('来源信道类型',select(['微信','企业微信']),true,true)}${field('来源信道',select(['平台共享微信信道','企业微信主信道']),true,true)}${field('启用','<button class="switch on"></button>')}${field('过期时间','<input class="control" type="datetime-local">',false,false,'留空表示永不过期')}</div>`)}`;
add('admin-system.html','系统设置',shell('系统设置','/admin/system',adminSystem,{admin:true}));

// Manifest / page inventory
const inventory=[
 ['公开页面',[['登录','login.html','/login'],['商户注册','register.html','/register'],['系统管理员登录','admin-login.html','/admin/login'],['扫码登录回调','admin-login-callback.html','/admin/login/callback'],['经营决策日报','daily-report.html','/daily-report'],['嵌入入口','embed.html','/embed'],['嵌入链路联调','embed-test.html','/embed-test']]],
 ['租户端',[['首页','home.html','/'],['订单录入','chat-simulator.html','/chat-simulator'],['订单审核','tasks.html','/tasks'],['录单工作台','order-board.html','/order-board'],['订单详情（Excel 多商品）','task-detail.html','/tasks/[id]'],['订单详情（单商品）','task-detail-single.html','/tasks/[id]'],['客户管理','customers.html','/customers'],['群聊管理','groups.html','/groups'],['群聊详情','group-detail.html','/groups/[id]'],['客户分组','customer-groups.html','/customer-groups'],['报价单','sku.html','/sku'],['提示词','prompts.html','/prompts'],['AI 记忆','memory.html','/memory'],['统计','stats.html','/stats'],['经营决策大屏','decision-dashboard.html','/decision-dashboard'],['设置','settings.html','/settings'],['回复设置','settings-replies.html','/settings/replies'],['信道详情','settings-channel-detail.html','/settings/channels/[channelId]']]],
 ['平台管理端',[['管理入口（兼容）','admin.html','/admin'],['租户管理','admin-tenants.html','/admin/tenants'],['系统管理员','admin-system-admins.html','/admin/system-admins'],['模版库','admin-presets.html','/admin/presets'],['统计分析','admin-stats.html','/admin/stats'],['案例详情','admin-stats-case.html','/admin/stats/case/[taskId]'],['系统设置','admin-system.html','/admin/system']]]
];
const inventoryBody=`<main style="max-width:1320px;margin:auto;padding:34px 24px"><div class="page-title"><div><h1>观麦 AI 智能订单助手 · 静态原型总览</h1><p>基于 apps/admin 全量路由梳理 · 31 个页面入口 · 纯 HTML / CSS / JavaScript，可离线打开编辑</p></div><span class="tag blue">生成日期 2026-07-14</span></div><div class="alert">点击页面卡片可直接预览。动态路由使用代表性示例数据；按钮、筛选、标签页、开关和弹窗均可交互演示。</div>${inventory.map(([group,items])=>`<section class="card"><div class="card-head">${group}<span class="help">${items.length} 个页面</span></div><div class="card-body"><div class="grid four">${items.map(([n,f,r])=>`<a class="app-card" href="${f}" style="text-decoration:none;color:inherit;text-align:left"><div style="font-size:16px;font-weight:600;margin-bottom:6px">${n}</div><div class="mono">${r}</div><div class="help" style="margin-top:8px">${f}　→</div></a>`).join('')}</div></div></section>`).join('')}</main>`;
add('index.html','静态原型总览',inventoryBody);

// Write all independent, self-contained HTML files.
for (const [file,html] of pages) fs.writeFileSync(path.join(outDir,file),html,'utf8');
fs.writeFileSync(path.join(outDir,'页面清单.txt'),inventory.flatMap(([g,items])=>[`【${g}】`,...items.map(([n,f,r])=>`${n}\t${r}\t${f}`),'']).join('\r\n'),'utf8');
console.log(`Generated ${pages.size} HTML files in ${outDir}`);

// Keep tenant prototypes pixel-aligned with the current admin frontend.
// Public and platform-admin pages above remain unchanged.
await import('./tenant-overrides.mjs');
